input_path: 'c:\Projects\risc_dse\data_fronius\input_files'
output_path: 'c:\Projects\risc_dse\data_fronius\parquet_files'
input_file_name: '*.tar.gz'
entry_point: 'main_p'
tmp_paths:
  - 'c:\Projects\risc_dse\data_fronius\csv_files\'
imports:
  - mcp_use_case_fronius.io_functions
  - mcp_use_case_fronius.transformation_functions
  - mcp_general_functions.mcp_general_io
  - mcp_general_functions.mcp_general_transformations
pipelines:
  - main_p:
    - list_dir:
        - { relative_path: True, output_for_iteration: True }
    - loop: unzip_p

  - unzip_p:
    - determine_end_date_from_filename_v2: ~
    - determine_output_filename: ~
    - unzip:
        - { 'output_into_next_tmp_folder': True }
    - set_default_input_from_variable:
        - { 'input_label': 'input_dir'}
    - list_dir:
        - { 'only_file_names_return': True, 'output_for_iteration': True }
    - processing_dirs_p: ~

    print_p:
    - print_all: ~

    processing_dirs_p:
    - loop_processing_csvs: read_input_data_p
    - resample_p: ~

    resample_p:
    - transformation_p: ~       # a pipeline can contain other pipelines
    - write_output_p: ~

    read_input_data_p:
    - read_csv_file: ~

    write_output_p:
    - write_to_parquet: ~

    transformation_p:
    - merging_columns: ~
