input_path: &base_dir '.'
output_path: *base_dir
entry_point: 'main_p'

further_configuration:   # This part only demonstrates, how to define key value pairs, but its content are not used
   - first_key_value_pair: value1
   - second_key_value_pair: value2
imports:
  - mcpf_io.io
  - mcpf_io.pd
pipelines:
  - main_p:
      - list_dir:
          - { relative_path: True, output_for_iteration: True }
      - loop: list_input_dirs_p
      - final_steps: ~

  - list_input_dirs_p:
      - processing_files_p: ~
      - list_dir:
          - {output_for_iteration: True }
      - loop: processing_files_p

  - processing_files_p:
      - print_to_stdout: ~

  - final_steps:
      - print_to_stdout:
          - {input: 'done.', is_literal: True}
