input_path: '../data_santub/excel_files'
output_path: '../data_santub/parquet_files'
entry_point: 'prepare_reports_p'
further_configuration:
  - default_value_note: 1
  - header:
      ['Jahr', 'Objekt Name', 'Baujahr', 'Pos.', 'Bauteil', 'Lokation', 'Schaeden', 'Anzahl Lokat.', 'Laenge (m)', 'Breite (m)', 'Material', 'Note', 'Anmerkung', 'Zustandnote', 'Y', 'X', 'Gesamtnote']

imports:
  - mcp_general_functions.mcp_general_transformations
  - mcp_general_functions.mcp_general_io
  - mcp_santub.transformation_functions
pipelines:
  - prepare_reports_p:
      - read_csv:
        - { relative_path: True, input_path: '..', 'output': 'coordinates', file_name: 'coordinates.csv' }
      - list_dir:
        - { relative_path: True, output_for_iteration: True }
      - loop: read_dirs_p

  - read_dirs_p:
      - list_dir:
        - { output_for_iteration: True }
      - loop: process_excel_p
      - set_default_file_name_from_data:
          - { input: 'dir_name', extension: '.parquet' }
      - write_parquet:
          - { input: 'all_object_with_the_same_type', relative_path: True }
      - remove_data:
          - { input: 'all_object_with_the_same_type' }

  - process_excel_p:
      - get_object_name: ~
      - read_excel_worksheets: ~
      - process_worksheet_data: ~
      - write_parquet:
          - { relative_path: True }
      - vertical_concatenation:
          - { left_value: 'all_object_with_the_same_type' }
