input_path: &base_dir 'C:\Workspace\mjahn\risc_dse\configurable_pipeline_frm\src\python\mcp_use_case_testing_duckdb'
output_path: *base_dir
entry_point: 'main_p'
imports:
  - mcp_general_functions.mcp_general_io
  - mcp_general_functions.mcp_general_transformations
pipelines:
  - main_p:
      - read_csv: 
          - { 'input_path': '..\mcp_use_case_testing_duckdb', 'file_name': 'testing_csv.csv'}
      - print_to_stdout: ~
      - df_sql_statement:
          - { 'SQL_STMT': 'SELECT * FROM data where id > 50 and id < 150;'}
      - print_to_stdout: ~
