input_path: 'c:\Projects\risc_dse\data\input_files\'
output_path: 'c:\Projects\risc_dse\data\parquet_files\'
input_file_name: '*.tar.gz'
entry_point: 'unzip_p'
tmp_paths:
  - 'c:\Projects\he_meta\data\csv_files\'
imports:
  - mcp_use_case_fronius.io_functions
  - mcp_use_case_fronius.transformation_functions
pipelines:
  - unzip_p:
    - unzip_all: ~                    # a pipeline can contain python functions
    - loop_processing_all_dir: processing_dirs_p    # the prefix loop is a keyword

    print_p:
    - print_all: ~

    processing_dirs_p:
    - determine_end_date_from_filename: ~
    - determine_output_filename: ~
    - loop_processing_csvs: read_input_data_p
    - resample_p: ~

    resample_p:
    - transformation_p: ~       # a pipeline can contain other pipelines
    - write_output_p: ~

    read_input_data_p:
    - read_csv_file: ~

    write_output_p:
    - write_to_parquet: ~

    transformation_p:
    - merging_columns: ~
