input_path: &base_dir 'c:\Projects\risc_dse\configurable_pipeline_frm\src\python\mcp_use_case_UPO\data'
output_path: *base_dir
entry_point: 'EQE_p'
further_configuration:
  - output_filename: 'testcsvsugg1'
imports:
  - mcp_general_functions.mcp_general_transformations
  - mcp_general_functions.mcp_general_io
  - mcp_use_case_UPO.EQE_computations
  - mcp_use_case_UPO.write_data
pipelines:
  - EQE_p:
    - read_help_tables_p: ~
    - list_dir:
      - {input_path: 'EQE\data\dut',
         relative_path: True,
         output_for_iteration: True}
    - loop: read_dut_files_p
    - list_dir:
      - {input_path: 'EQE\data\calibration_fotodiode',
         relative_path: True,
         output_for_iteration: True}
    - loop: read_fotodiode_files_p
    - initialization_p: ~
    - loop_calculation: calculation_core_p
    - compose_output_p: ~

  - read_help_tables_p:
    - read_csv:
        - { file_name: 'Hamamatsu_PhotoDiode_Spectral_Response.csv',
            input_path: 'help_table',
            separator: ';',
            relative_path: True }
    - interpolate_first_column:
        - { output: 'help_df_hamamatsu', step: 5 }
    - read_csv:
        - { file_name: 'Reference_Spectra_Derived.csv',
            input_path: 'help_table',
            separator: ';',
            relative_path: True,
            output: 'help_df_referance' }

  - read_dut_files_p:
    - read_csv:
      - {input_path: 'EQE\data\dut',
         separator: '\t| ',
         skip_rows: 1,
         engine: 'python'}
    - vertical_concatenation:
      - {left_value: 'df_dut'}

  - read_fotodiode_files_p:
    - read_csv:
      - {input_path: 'EQE\data\calibration_fotodiode',
         separator: '\t| ',
         skip_rows: 1,
         engine: 'python' }
    - vertical_concatenation:
      - { left_value: 'df_fotodiode' }

  - initialization_p:
     - init_calc_eqe_perc: ~
     - init_calc_integral_current_density: ~

  - calculation_core_p:
     - calculate_eqe_perc: ~
     - calculate_electron_flux: ~
     - calculate_integral_current_density: ~
     - feedback_on_std_out: ~

  - compose_output_p:
     - compose_output: ~
     - write_eqe_sol1: ~
